// Code generated by Slice Machine. DO NOT EDIT.

import BasicHero from './BasicHero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	basic_hero: BasicHero,
	rich_text: RichText
};
